name = "meta-site-vue"
compatibility_date = "2025-03-18"

main = "./functions/contact.ts"

# Routes configuration
[routes]
pattern = "meta-site-vue.anandncs.workers.dev/*"
script = "./functions/contact.ts"

# Enable CORS
[configuration]
cors = true

[build]
command = ""
cwd = "."
upload.format = "modules"