name = "meta-site-vue"  # Worker name
type = "javascript"     # Worker type (JS-based worker)
compatibility_date = "2025-03-18"  # Adjust to the current date

# Entry point for the worker script
main = "./functions/contact.ts"  # The TypeScript file path

# Routes
routes = [
  { pattern = "*metazapp.com/api/contact*", zone_name = "metazapp.com" }
]

# Build settings
[build]
command = "npm install && npm run build"  # Add build steps if necessary
upload.format = "service-worker"  # Ensure that it's a service worker
upload.dir = "./functions"  # Specify the directory with the worker script