name = "meta-site-vue.workers.dev"       # Worker name
type = "javascript"              # Worker type (JS-based worker)
compatibility_date = "2025-03-18" # Adjust to the current date

# Entry point for the worker script
main = "./functions/contact.ts"     # Replace with your script path

# Define the GitHub build settings
[build]
command = "npm install && npm run build"   # Add build steps if necessary
upload.format = "service-worker"
upload.dir = "./functions"         # Specify the directory with the worker script
